# Generated by Django 3.2.5 on 2021-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='textComment',
            field=models.TextField(default='Nothing'),
        ),
    ]
